rosbag:
  rosbag_dir: D:\data\rosbag_dex_hand_10_20250805_4800
  num_used: None
  lerobot_dir: D:\data\rosbag_dex_hand_10_20250805_4800_lerobot

dataset:
  only_arm: true  # 默认true, 是否只使用手臂数据, 目前的模仿学习只用于手臂数据
  eef_type: dex_hand # or leju_claw
  which_arm: both  # 可选: left, right, both

  # task_description: "Pick the black workpiece from the white conveyor belt on your left and place it onto the white box in front of you"
  task_description: "Place the black workpiece from the white desk onto the electronic scale, then move the it to the left white conveyor belt"

  train_hz: 10  # 训练采样频率
  main_timeline_fps: 30 # 主相机的帧率，必须稳定, 主相机来自head_cam_h, wrist_cam_l, wrist_cam_r
  sample_drop: 10 # 丢弃回合前后的10帧

  # dex_dof_needed是强脑手需要的自由度数目。强脑灵巧手有6个自由度。标准握拳状态[100] * 6, 张开状态[0] * 6。
  # 1: 不需要精细操作或者多指协同操作时，通常为设置为1，表示只需要第一个关节作为开合依据,此时需要用[0, 100, 0, 0, 0, 0]表示张开状态, [100] * 6表示握拳状态。
  # 2(暂未测试): 或者设置为2，目前的手柄遥操作只有两个自由度。0,2,3,4,5自由度绑定为1个自由度。
  # 6(暂未测试): 如果脱离手柄使用手指灵巧操作，可以设置为6，表示需要所有6个自由度。
  dex_dof_needed: 1   # default=1

  is_binary: false  # 是否将开合二值化, default=false
  delta_action: false # 是否使用增量动作，default=false
  relative_start: false # 是否使用相对起始位置, default=false

  resize:
    width: 848
    height: 480



