use_delta: false
eval_episodes: 100
seed: 42
device: "cuda"  # or "cpu"
task: "aloha_sim_insertion_human"
method: "new_model"
timestamp: "run_20250814_204035"
epoch: 679
max_episode_steps: 300
env: aloha
